import readBold from "@/public/icons/read-me2.svg";
import read from "@/public/icons/read-me3.svg";
import Image from "next/image";
import email from "@/public/icons/email.svg";

export default function InfoButtons() {
  return (
    <>
      <button
        className="absolute top-8 lg:top-8 sm:top-[58px] max-lg:left-[54px] lg:right-[64px] max-sm:left-[30px] w-6 h-6 rounded-full lg:text-white text-[#ccbfa7] text-sm bg-[#ebe5cdb1] lg:bg-[#105edc] hover:scale-105 transition-transform duration-100 active:scale-90 lg:shadow-sm font-textarea font-extrabold"
        onClick={() => document.getElementById("how-to-modal").showModal()}
      >
        i
      </button>
      <button
        className="absolute lg:hidden top-8 sm:top-[58px] sm:right-[54px] right-[30px] w-6 h-6 rounded-full hover:scale-105 transition-transform duration-100 active:scale-90"
        onClick={() => document.getElementById("about-modal").showModal()}
      >
        <Image alt="infomation" src={read} />
      </button>
      <button
        className="absolute max-lg:hidden top-[32px] right-8 w-[25px] h-[25px]  rounded-full shadow-sm hover:scale-105 transition-transform duration-100 active:scale-90"
        onClick={() => document.getElementById("about-modal").showModal()}
      >
        <Image alt="infomation" src={readBold} />
      </button>

      {/* Modals */}

      <dialog id="about-modal" className="modal bg-[#0000006c]">
        <div className="bg-white p-1.5 rounded-xl relative">
          <div className="bg-gold-animation p-1.5 rounded-lg min-w-52 min-h-52">
            <div className="bg-gold-200 rounded-md p-6 max-w-sm mx-auto">
              <h2 className="text-center font-extrabold text-[18px] text-[#bda03e] mb-2">
                Generate a trading message for <br /> MOGO cards in just a few
                clicks
              </h2>
              <h2 className="text-center font-bold text-[17px] text-[#61605e] mb-2">
                Make them searchable & boost visibility
                <br /> to more people!
              </h2>

              <ul className="mb-4 text-gray-300">
                <li>
                  ✦ Design elements and card references from the mobile game{" "}
                  <a
                    href="https://apps.apple.com/us/app/monopoly-go/id1621328561"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="font-bold hover:underline text-[#c8a73b]"
                  >
                    Monopoly Go!
                  </a>
                </li>
                <li>
                  ✦ The logo generated by ChatGPT to save time, as this is a
                  side project for applying to an entry-level full-stack
                  developer position.
                </li>
              </ul>

              <h2 className="font-bold mb-1 text-[#61605e]">Next Update:</h2>
              <ul className="text-gray-300">
                <li>✧ Login account to save selected cards</li>
              </ul>
              <a
                className="contact text-[#ccbfa7] hover:text-[#ad9f85] mt-2 w-full flex gap-2 items-center"
                href="mailto:monomycards@gmail.com"
              >
                <Image
                  src={email}
                  alt="email"
                  onClick="mailto:monomycards@gmail.com"
                  width={17}
                  height={17}
                />
                Contact
              </a>

              <form method="dialog">
                <button className="btn-sm btn-circle absolute right-[50%] translate-x-1/2 -bottom-12 text-[#9f9777ed] hover:text-[#d3caa4ed] font-extrabold text-lg border-2 border-[#867a50d8] hover:border-[#ae9d5dd8]">
                  X
                </button>
              </form>
            </div>
          </div>
        </div>
      </dialog>

      <dialog id="how-to-modal" className="modal bg-[#0000006c]">
        <div className="bg-white p-1.5 rounded-xl relative">
          <div className="bg-gold-animation p-1.5 rounded-lg min-w-52 min-h-fit">
            <div className="bg-gold-200 rounded-md p-6 max-w-lg mx-auto">
              <h2 className="text-center font-extrabold text-[18px] text-[#bda03e] mb-2">
                Just click the card to change its status:
              </h2>
              <p className="mb-2 text-center font-bold text-[#61605e]">
                Default&nbsp; ➞ &nbsp;Have duplicate&nbsp; ➞ &nbsp;Need
              </p>
              <h2 className="text-center font-extrabold text-[17px] text-gray-400 mb-2">
                Then, copy the text to share with your community
              </h2>

              <form method="dialog">
                <button className="btn-sm btn-circle absolute right-[50%] translate-x-1/2 -bottom-12 text-[#9f9777ed] hover:text-[#d3caa4ed] font-extrabold text-lg border-2 border-[#867a50d8] hover:border-[#ae9d5dd8]">
                  X
                </button>
              </form>
            </div>
          </div>
        </div>
      </dialog>
    </>
  );
}
